### ISSUE TITLE
Use of SVG logos

### ISSUE THREAD

**Issue by edhenderson** [jimniels/teamcolors#67]
Hi @jimniels - first of all, what a great wee project this is. Thank you for sharing it.

I am working on my own wee single page app / project to teach myself better React. Its on a similar theme to yourself. I came across your repo as I was trying to find logos of the teams and you have a great collection (and well sourced).

I was wondering if I would be able to use them in my personal (hopefully one day, commercial) project? More than happy to credit you appropriately (I did look for a License but I couldn't see one, sorry).

Thank you Sir and keep up the good work.

**Comment by jimniels** [comment]
Hello @edhenderson Thanks for the kind words. I'm glad you've found this project useful!

From my standpoint, feel free to use these logos however you want. However, with that said, I'm not fully aware of the legal aspects of your intended usage. Because all of these logos are the intellectual property of their respective teams, I would venture to guess that if you're going to use them for commercial project, you'd likely be entering murky, licensing waters where you should be paying for use of team logos. For this particular open project, because no money is being made, I see it as falling under fair use until someone suggests otherwise. But I'm not a lawyer and that's just my two cents.

Also, "add a license to the project" will end up being on my to-do list.

**Comment by edhenderson** [comment]
@jimniels

I completely agree with your point about logos. My thing as at the point where I am still exploring, having fun and trying to even work out if what I have is even commercially viable. Even if it *ever* does, it would be done in such a way that if the logos were unavailable, the system/design/process wouldn't break. Thanks for your concern Sir.

I also saw you had colour codes, which is awesome. I don't know if you've ever seen http://teamcolorcodes.com/ (not mine), also a good resource.

**Comment by jimniels** [comment]
I have seen [teamcolorcodes.com](http://teamcolorcodes.com/), but [the site based on this repo](http://jim-nielsen.com/teamcolors) is better in my (obviously unbiased) opinion ;)

**Comment by edhenderson** [comment]
Touche! Great stuff, thanks again and I'll ping you my project when its ready for a peek.
